version: '3.8'

services:
  db:
    image: mysql:5.6.35
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_DATABASE=spyle
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - db-network
  
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    links:
      - db
    networks:
      - db-network
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: db
            port: 3306
            user: root
            password: root
            migrations: true
    depends_on:
      - db

  app:
    depends_on:
      - prisma
    image: api_graphql
    ports:
      - "4200:4200"
    restart: always
    links:
      - db
    networks:
      - db-network
    env_file:
      - .env

networks:
  db-network:
    driver: bridge

volumes:
  db_data: {}