version: '3'

services:
  db:
    image: mysql:5.6.35
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_DATABASE=spyle
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: db
            port: 3306
            user: root
            password: root
            migrations: true
    volumes:
      - prisma_data:/prisma
    depends_on:
      - db

  app:
    depends_on:
      - db
    image: api_graphql
    ports:
      - "4200:4200"
    restart: always
    env_file:
      - .env
volumes:
  db_data: {}
  prisma_data: {}