name: CI

on:
  push:
    branches:
      - main
      - dev
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: switch node version to 16.15.1
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      
      - name: install dependencies
        run: 
          yarn install

      - name: build app
        run : | 
          yarn build 
          


